---
# Information about version of nixos-cloud-init-installer, to manually update
# renovate: datasource=github-releases depName=AnarchoBooleanism/nixos-cloud-init-installer
nixos_cloudinit_iso_version: v2.6.0
nixos_cloudinit_iso_name: "nixos-cloud-init-installer-{{ nixos_cloudinit_iso_version }}-x86_64.iso"
nixos_cloudinit_iso_url: "https://github.com/AnarchoBooleanism/nixos-cloud-init-installer/releases/download/\
  {{ nixos_cloudinit_iso_version }}/{{ nixos_cloudinit_iso_name }}"
nixos_cloudinit_user: root

# Important details for deploying with nixos-anywhere and updating flakes
nixos_anywhere_build_remotely: false # You're free to enable this if the target system is powerful enough, or if building locally causes problems
nixos_anywhere_target_minimum_memory: 2048 # In MiB, as going under this may lead to freezing
nixos_rebuild_build_remotely: false # You're free to enable this if the target system is powerful enough, or if building locally causes problems
ssh_port: 22
uses_impermanence: false
uses_sopsnix: false

# The Git repository to refer to for NixOS flakes
nixos_flake_repo: github:anarchobooleanism/saphnet-nixos-configs
nixos_flake_repo_url: https://github.com/AnarchoBooleanism/saphnet-nixos-configs.git
nixos_flake_repo_branch: main

# Important info for logging in
nixos_username: cicd # Default NixOS username here
