---
- name: Update NixOS-based virtual machines
  hosts: localhost
  connection: local
  # vars_files:
  #   - ../../secrets/ansible.enc.yaml
  tasks:
    - name: Set initial list of VMs to process
      ansible.builtin.set_fact:
        vm_list: "{{ groups['nixos_hosts'] }}"
    - name: Set final list of VMs to process
      ansible.builtin.set_fact:
        final_vm_list: >-
          {{
            [target_vm_name]
            if target_vm_name is defined
            else vm_list
          }}
    - name: Load NixOS-specific configuration file
      ansible.builtin.include_vars:
        file: "../../group_vars/nixos_vms.yaml"
    - name: Create directory for logs from nixos-rebuild
      ansible.builtin.file:
        path: "../../tmp-logs"
        state: directory
    - name: Update each VM # This is the main guts of our logic here
      include_tasks: internal-loop.yaml
      loop: "{{ final_vm_list }}"
      loop_control:
        loop_var: vm_file
