name: ansible-lint
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths-ignore:
      - '.github/**' # Avoid issues with .github files
      - 'docs/**'
      - 'prod-shell/**'
      - 'secrets/**'
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'prod-shell/**'
      - 'secrets/**'

jobs:
  lint:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Run ansible-lint
        uses: ansible/ansible-lint@665d9e07a1943254d2910faffc106adaf7ea7294 # v26
        with:
          args: "--exclude secrets common_files" # Prefer to not deal with vault secrets
        continue-on-error: true
